version: '3'
services:
  stubby:
    container_name: stubby
    build: stubby
    networks:
      dns:
        ipv4_address: 172.39.0.2
    restart: unless-stopped
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'Europe/Paris'
      DNS1: '172.39.0.2#8053'
      DNS2: 'no'
      DNS_BOGUS_PRIV: 'false'
      DNS_FQDN_REQUIRED: 'true'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './pihole/etc-pihole:/etc/pihole/'
      - './pihole/etc-dnsmasq:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
    networks:
      dns:
        ipv4_address: 172.39.0.3

networks:
  dns:
    ipam:
      driver: default
      config:
        - subnet: "172.39.0.0/24"
